### ISSUE TITLE
M2M Transformation/Interpretation

### ISSUE THREAD

**Issue by Akons97** [janschill/mosyl_2020_group2#8]
For defining M2M transformations, you may use any of the dedicated technologies (e.g., QVT-O or ATL) or a GPL such as Java.
- [x] For the transformation of GT’s Station Plan model to PTS’s Network model, dedicated technologies (e.g., QVT-O or ATL) are adequate.
- [ ] For the transformation of Schedule to Timetable models, the use of Java is advisable.

**Comment by janschill** [comment]
I finished the transformation of StationPlan to Network in PR https://github.com/janschill/mosyl_2020_group2/pull/19.
